version: "3.0"
services:
    apache:
    image: httpd:latest
    container_name: apache
    ports:
        - "81:80"
    volumes:
        - ./website:/usr/local/apache2/htdocs
	
    web:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80